### ISSUE TITLE
arel, gem_patching want's 2.0.6

### ISSUE THREAD

**Issue by kylef** [svenfuchs/adva-cms2#1]
When I use thor to generate a new app I get the following error:

```
/Users/kylef/.rvm/gems/ruby-1.8.7-p302/gems/gem_patching-0.0.2/lib/gem_patching.rb:7:in `patching': Attempt to apply patch targeting version '2.0.6' of 'arel', but active version is '2.0.7' (RuntimeError)
from /Users/kylef/git/adva-cms2/adva-core/lib/patches/arel_in_subquery.rb:4
```

I have tried installing 2.0.6 and removing 2.0.7 but then I get another issue:

```
WARNING: unable to load thorfile "/Users/kylef/git/adva-cms2/Thorfile": Could not find arel-2.0.7 in any of the sources
```
- 8765377a0b2bdf892e3a276a0d4d59253a56989b

**Comment by kronn** [comment]
thanks for the report.

Our CI server reports this as well (now) and we're working on it.

Your second issue seems to be related to bundler, I think. Have you also removed the Gemfile.lock?

**Comment by khallmark** [comment]
I was able to get it running by removing the Gemfile.lock file.

**Comment by kronn** [comment]
cool.

Also, Ingo (ingoweiss) fixed this in develop. The next release will depend on arel 2.0.6 untill we can adjust our version-specific (yet needed) patch.

thanks again for reporting the issue.
