### ISSUE TITLE
undefined method `as' for #<Arel::Table

### ISSUE THREAD

**Issue by artofwar** [svenfuchs/adva-cms2#2]
when i go to to the localhost and i create a new page 
its give this error and i could not fix this error mesagge

undefined method `as' for #Arel::Table:0x7e30f1b4

Rails.root: /home/jonathanandrades/jonathan/adva_app

Application Trace | Framework Trace | Full Trace

simple_nested_set (0.0.28) lib/simple_nested_set/nested_set.rb:137:in `denormalize_level_query'
simple_nested_set (0.0.28) lib/simple_nested_set/nested_set.rb:60:in`denormalize!'
simple_nested_set (0.0.28) lib/simple_nested_set/nested_set.rb:48:in `save!'
simple_nested_set (0.0.28) lib/simple_nested_set/act_macro.rb:16:in`_callback_after_342'
activesupport (3.0.3) lib/active_support/callbacks.rb:430:in `_run_save_callbacks'
activerecord (3.0.3) lib/active_record/callbacks.rb:277:in`create_or_update'
activerecord (3.0.3) lib/active_record/persistence.rb:39:in `save'
activerecord (3.0.3) lib/active_record/validations.rb:43:in`save'
activerecord (3.0.3) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (3.0.3) lib/active_record/transactions.rb:237:in`save'
activerecord (3.0.3) lib/active_record/transactions.rb:289:in `with_transaction_returning_status'
activerecord (3.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:139:in`transaction'
activerecord (3.0.3) lib/active_record/transactions.rb:204:in `transaction'

**Comment by kronn** [comment]
Thanks for reporting this error.

This issue is related to an incompatibility between certain versions of simple_nested_set and arel. The current release of adva-cms2 depends on a newer version which resolves this.

**Comment by svenfuchs** [comment]
Should be fixed with the current release.
